name: basic_dart
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/maulanasdqn/basic-dart

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

# Add dev dependencies here.
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
